import { NextRequest, NextResponse } from 'next/server'
import { hashPassword } from '@/lib/auth'
import { saveUser, getUserByEmail } from '@/lib/data'
import { ratelimit } from '@/lib/rateLimit';




export async function POST(request: NextRequest) {


  try {
    const { fullName, email, ghanaCard, studentId, password, ghanaCardImage, studentIdImage , vericationCode } = await request.json()
  const identifier = email || request.headers.get('x-forwarded-for')
  console.log('identifier for rate limiting:', identifier);
    if (!fullName || !email || !password || !ghanaCard || !studentId || !ghanaCardImage || !studentIdImage) {
      console.log('Missing fields:', { fullName, email, password, ghanaCard, studentId, ghanaCardImage, studentIdImage })
      return NextResponse.json(
        { error: 'All fields are required, including document images' },
        { status: 400 }
      )
    }


  const { success, limit, remaining, reset } =
  await ratelimit.limit(identifier);

if (!success) {
  return NextResponse.json(
    { error: 'Too many requests, please try again later.' },
    {  
      status: 429, 
      headers: {
      "X-RateLimit-Limit": limit.toString(),
      "X-RateLimit-Remaining": remaining.toString(),
      "X-RateLimit-Reset": reset.toString(),
    }
     },
    
    
  );
}



    // Check if user already exists
    const existingUser = await getUserByEmail(email)
    if (existingUser) {
      return NextResponse.json(
        { error: 'User already exists' },
        { status: 400 }
      )
    }

    // Hash password
    const hashedPassword = await hashPassword(password)

    // Create user (MongoDB will generate the ID)
    const user = {
      id: '', // Will be generated by MongoDB
      fullName,
      email,
      ghanaCard,
      studentId,
      ghanaCardImage,
      studentIdImage,
      password: hashedPassword,
      role: 'student' as const,
      isEmailVerified: false,
      agreedToTerms:false,
    }

   

   
    
    await saveUser(user)

    return NextResponse.json(
      { message: 'User registered successfully' },
      { status: 201 }
    )
  } catch (error) {
    console.error('Registration error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}


